version: '3.8'

services:
  app:
    build: .
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - laravel_net
    environment:
      APP_ENV: production
      APP_DEBUG: "false"
      DB_CONNECTION: pgsql
      DB_HOST: dpg-cusvkglumphs73cdj8b0-a.oregon-postgres.render.com
      DB_PORT: 5432
      DB_DATABASE: psyassdb
      DB_USERNAME: psyassdb_user
      DB_PASSWORD: defXqspTe5tziXfCjsXlirWEjNqGOSJe

  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel_net

networks:
  laravel_net:
