version: '3.8'

services:
  app:
    build: .
    container_name: laravel_api
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"
    environment:
      APP_ENV: production
      APP_DEBUG: "false"
      DB_CONNECTION: pgsql
      DB_HOST: dpg-cusvkglumphs73cdj8b0-a.oregon-postgres.render.com
      DB_PORT: 5432
      DB_DATABASE: psyassdb
      DB_USERNAME: psyassdb_user
      DB_PASSWORD: defXqspTe5tziXfCjsXlirWEjNqGOSJe
